all:
  children:
    k3s_cluster:
      children:
        control_plane:
          hosts:
            kubernetes-control-plane-node:
              ansible_host: 192.168.2.16
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
              node_ip: 192.168.2.16
        workers:
          hosts:
            kubernetes-worker-node :
              ansible_host: 192.168.2.17
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
              node_ip: 192.168.2.17
      vars:
        ansible_python_interpreter: /usr/bin/python3
